import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pos_billing/core/constants/app_constants.dart';
import 'package:pos_billing/core/services/pdf_fonts.dart';
import 'package:pos_billing/shared/models/store_profile.dart';
import 'package:share_plus/share_plus.dart';

class ReportsPdfExporter {
  Future<void> exportAndShare({
    required StoreProfile store,
    required String rangeLabel,
    required int todaySalesPaise,
    required int billsToday,
    required int stockValuePaise,
    required int expensesPaise,
    required Map<String, int> payments,
    required List<(String name, int qty, int salesPaise)> topProducts,
  }) async {
    final theme = await PdfFonts.theme();
    final doc = pw.Document(theme: theme);
    final generatedAt =
        DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now());

    pw.Widget kv(String k, String v, {bool bold = false}) {
      return pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              k,
              style: pw.TextStyle(
                fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
              ),
            ),
            pw.Text(
              v,
              style: pw.TextStyle(
                fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
              ),
            ),
          ],
        ),
      );
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Text(
            store.name,
            style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text('Business Report'),
          pw.Text('Period: $rangeLabel'),
          pw.Text('Generated: $generatedAt'),
          pw.SizedBox(height: 16),
          pw.Divider(),
          pw.SizedBox(height: 12),
          pw.Text(
            'Summary',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          kv('Today sales', pdfMoney(todaySalesPaise)),
          kv('Bills today', '$billsToday'),
          kv('Stock value', pdfMoney(stockValuePaise)),
          kv('Expenses', pdfMoney(expensesPaise)),
          pw.SizedBox(height: 16),
          pw.Text(
            'Collections',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          kv('CASH', pdfMoney(payments[PaymentMethods.cash] ?? 0)),
          kv('UPI', pdfMoney(payments[PaymentMethods.upi] ?? 0)),
          kv('CARD', pdfMoney(payments[PaymentMethods.card] ?? 0)),
          kv('CREDIT', pdfMoney(payments[PaymentMethods.credit] ?? 0)),
          pw.SizedBox(height: 16),
          pw.Text(
            'Top products',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          if (topProducts.isEmpty)
            pw.Text('No sales in this period')
          else
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(3),
                1: const pw.FlexColumnWidth(1),
                2: const pw.FlexColumnWidth(1.5),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _cell('Product', bold: true),
                    _cell('Qty', bold: true, align: pw.TextAlign.right),
                    _cell('Sales', bold: true, align: pw.TextAlign.right),
                  ],
                ),
                for (final item in topProducts)
                  pw.TableRow(
                    children: [
                      _cell(item.$1),
                      _cell('${item.$2}', align: pw.TextAlign.right),
                      _cell(pdfMoney(item.$3), align: pw.TextAlign.right),
                    ],
                  ),
              ],
            ),
          pw.SizedBox(height: 24),
          pw.Center(
            child: pw.Text(
              'Generated by POS Billing',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final stamp = DateFormat('yyyyMMdd_HHmm').format(DateTime.now());
    final file = File('${dir.path}/report_$stamp.pdf');
    await file.writeAsBytes(await doc.save());
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path, mimeType: 'application/pdf')],
        text: '${store.name} report - $rangeLabel',
        subject: '${store.name} Report',
      ),
    );
  }

  pw.Widget _cell(
    String text, {
    bool bold = false,
    pw.TextAlign align = pw.TextAlign.left,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }
}
